#version: "3.8"

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    env_file:
      - .env
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - db_net


  wordpress:
    image: wordpress:php8.1-fpm
    container_name: wordpress
    restart: always
    env_file:
      - .env
    volumes:
      - ./data/wordpress:/var/www/html
    depends_on:
      - mysql
    networks:
      - db_net      # Acceso a MySQL
      - web_net     # Acceso a nginx


  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/wordpress:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - wordpress
    networks:
      - web_net

networks:
  db_net:
    driver: bridge
    # Red interna: MySQL, WordPress, phpMyAdmin
    # No expone puertos al exterior
  web_net:
    driver: bridge
    # Red frontend: nginx, WordPress
    # nginx expone puertos 80/443

