#version: "3.8"

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    env_file:
      - .env
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - db_net


  wordpress:
    image: wordpress:php8.1-fpm
    container_name: wordpress
    restart: always
    env_file:
      - .env
    volumes:
      - ./data/wordpress:/var/www/html
    depends_on:
      - mysql
    networks:
      - db_net      # Acceso a MySQL
      - web_net     # Acceso a nginx


  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/wordpress:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - wordpress
    networks:
      - web_net


  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    env_file:
      - .env
    ports:
      - "127.0.0.1:8080:80"  # Solo accesible desde localhost (no desde internet)
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - mysql
    networks:
      - db_net
    # Acceso local para administraci√≥n de BD
    # Nota: NO expone a internet (cumple requisito de solo puertos 80, 443, 22)

networks:
  db_net:
    driver: bridge
    # Red interna: MySQL, WordPress, phpMyAdmin
    # No expone puertos al exterior
  web_net:
    driver: bridge
    # Red frontend: nginx, WordPress
    # nginx expone puertos 80/443

