- name: Actualizar repositorio de paquetes
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Instalar dependencias necesarias
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - ubuntu-keyring
    state: present
- name: Crear directorio para claves GPG
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Descargar clave GPG de Docker
  apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    keyring: /etc/apt/keyrings/docker.asc
    state: present

- name: Agregar repositorio de Docker
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present

- name: Instalar Docker
  apt:
    name: docker.io
    state: present

- name: Instalar Docker Compose
  apt:
    name: docker-compose
    state: present

- name: Iniciar servicio Docker
  systemd:
    name: docker
    state: started
    enabled: yes
