- name: Actualizar repositorio de paquetes
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Instalar dependencias necesarias
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release -cs
      - ubuntu-keyring
    state: present

- name: Add Docker repository (busca la línea que agrega el repositorio y cambia focal por tu versión actual)
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"

- name: Instalar Docker
  apt:
    name: docker-io
    state: present

- name: Instalar Docker Compose
  apt:
    name: docker-compose
    state: present

- name: Iniciar servicio Docker
  systemd:
    name: docker
    state: started
    enabled: yes
